### ISSUE TITLE
Problem opeining the http server on windows

### ISSUE THREAD

**Issue by mohasafra** [smiclea/brackets-http-server#5]
when the new tab window opens it only shows

Not found see screenshot attached
![screenshot](https://cloud.githubusercontent.com/assets/10555252/7513944/8d95ef98-f4b0-11e4-95f8-be6695896cf3.jpg)

**Comment by smiclea** [comment]
That is strange. I'll have a look at it, some colleague of mine was able to reproduce it.

**Comment by mohasafra** [comment]
yes exactly I've checked the code me and a couple of friend and we couldn't understand the source of the problem...

**Comment by smiclea** [comment]
The problem was that most likely your path contains space. This is now resolved in latest version

**Comment by mohasafra** [comment]
yep that fixed it thanks a lot for your work
